[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes ",
    "apt-get update && apt-get install -y pkg-config libudev-dev:$CROSS_DEB_ARCH"
]

[target.arm-unknown-linux-gnueabi]
pre-build = [
    "apt-get update && apt-get install -y pkg-config wget",
    "apt-get update && apt-get install --assume-yes ",
    "apt-get update && apt-get install -y pkg-config libudev-dev:$CROSS_DEB_ARCH"
]